name: build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build
      run: go test -v ./...
  build-docker:
    needs: [test]
    runs-on: ubuntu-latest
    name: build container image and push
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: oliviermichaelis
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/oliviermichaelis/frontend:master
  deploy:
    needs: build-docker
    runs-on: ubuntu-latest
    container:
      image: bitnami/kubectl
    steps:
      - name: create .kube directory
        run: mkdir -p ~/.kube
      - name: Store kubeconfig
        shell: sh
        env:
          KUBECONFIG_FULL: ${{ secrets.OKTETO_KUBECONFIG }}
        run: 'echo $KUBECONFIG_FULL} | base64 -d > ~/.kube/config'
      - uses: actions/checkout@v2
      - name: Deploy
        run: kubectl apply -f kubernetes-manifests/frontend.yaml
